### PR TITLE
cycle3_improvements

### PR DESCRIPTION
**Pull request by the-zebulan**
I came to this repo to do this `cycle & islice` version but @serprex beat me to it! Although it may be more of a style choice, I moved the imports outside of the function and fixed a few `PEP8` warnings that came up on PyCharm.

```
PEP8: Line too long
PEP8: Missing whitespace after character ':'
PEP8: Multiple statements on one line
```

Also, the variable name `x` was being used twice as the function argument and as the iterating variable.

Thanks for your blogpost, @DangerOnTheRanger. I actually learned a couple new ways of doing `FuzzBuzz`!

### CODE REVIEW

**Comment by serprex** [comment]
Looks good. Very weird that a LOAD_GLOBAL op would be faster than a LOAD_CONST op tho

**Comment by the-zebulan** [comment]
I was just using `timeit.timeit` for the time, I should probably go dig a little deeper and figure out what exactly made the biggest difference. Whether it was just moving the import and/or moving the sequence outside of the function, I can't say for sure (right now).

**Comment by the-zebulan** [comment]
@serprex 
I did not realize that the import calls inside a function were cached the first time the function is called. I guess I was just used to putting them at the top. I've been doing some reading and some more testing. I removed the global variable `SEQ` and moved it back inside `cycle` just like you had it. In these SO questions, most of the comments seem to agree on putting the imports at the top but they do mention cases where it may be better to put them inside a function. I don't know if this is one of those cases, maybe you could clarify that part?
- https://stackoverflow.com/questions/3095071/in-python-what-happens-when-you-import-inside-of-a-function
- https://stackoverflow.com/questions/128478/should-python-import-statements-always-be-at-the-top-of-a-module

After adjusting how I was testing, the numbers seem to go back and forth as to which version is faster but they are so close I don't know how to judge.

Using `python -m timeit -n 10000 "code here"`:
- Imports inside function: `10000 loops, best of 3: 499, 513, 518 usec per loop`
- Imports at the top: `10000 loops, best of 3: 500, 511, 514 usec per loop`

Thank you for your comment about LOAD_GLOBAL & LOAD_CONST. It pointed me in the right direction and helped me learn a few things today. I obviously have lots left to learn about Python!

**Comment by DangerOnTheRanger** [comment]
Huh, interesting. Thanks for the improvements, @the-zebulan !

**Comment by serprex** [comment]
The rule of thumb is that if you use a function many times it's faster to be inside the function because then it'll be bound to a LOAD_FAST which is an array access rather than a LOAD_GLOBAL which is a hash access. In these cases we're talking 1 load so it gets overtaken by the import opcodes. If you want to dig into Python perf it's very transparent between the modules cProfile, timeit, & dis

**Pull request merged**
